function obj(v,n){if(!v||typeof v!=='object'||Array.isArray(v))throw new TypeError(`${n} must be an object`);return v}
function arr(v){return Array.isArray(v)?[...v]:[]}
function text(v){return String(v??'')}
function normalized(v){return text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function includesFact(answer,fact){const a=normalized(answer);const f=normalized(fact).trim();if(!f)return true;if(/^[-+]?\d+(?:[.,]\d+)?$/.test(f))return new RegExp(`(^|[^0-9])${f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^0-9]|$)`).test(a);return a.includes(f)}
function readPath(value,path){return String(path).split('.').filter(Boolean).reduce((current,key)=>current?.[key],value)}
export function normalizeEvaluationSuite(value){obj(value,'evaluation suite');if(typeof value.name!=='string'||!value.name.trim())throw new TypeError('name is required');if(!Array.isArray(value.providers)||value.providers.length===0)throw new TypeError('providers are required');if(!Array.isArray(value.cases)||value.cases.length===0)throw new TypeError('cases are required');const cases=value.cases.map((c,i)=>{obj(c,`case ${i}`);if(typeof c.id!=='string'||!c.id.trim())throw new TypeError('case id is required');if(typeof c.prompt!=='string'||!c.prompt.trim())throw new TypeError('case prompt is required');return {id:c.id,prompt:c.prompt,expected:c.expected??null,vars:{...(c.vars??{})}}});const threshold=value.threshold??1;if(!Number.isFinite(threshold)||threshold<0||threshold>1)throw new RangeError('threshold must be between 0 and 1');return {name:value.name,providers:[...value.providers],cases,threshold}}
export function buildPromptfooConfig(value){const suite=normalizeEvaluationSuite(value);return {description:suite.name,prompts:['{{prompt}}'],providers:suite.providers,tests:suite.cases.map(c=>({description:c.id,vars:{...c.vars,prompt:c.prompt},assert:c.expected==null?[]:[{type:'contains',value:String(c.expected)}]}))}}
export function summarizeEvaluation(results){if(!Array.isArray(results))throw new TypeError('results must be an array');const total=results.length;const passed=results.filter(r=>r?.pass===true).length;return {total,passed,failed:total-passed,passRate:total?passed/total:0}}
export async function executeEvaluation(adapter,value){if(typeof adapter?.run!=='function')throw new TypeError('evaluation adapter must expose run');const config=buildPromptfooConfig(value);const output=await adapter.run(config);return {...output,summary:summarizeEvaluation(output?.results??[])}}

export function normalizeFactRegressionCase(value){obj(value,'fact regression case');if(typeof value.id!=='string'||!value.id.trim())throw new TypeError('case id is required');const question=text(value.question??value.prompt).trim();if(!question)throw new TypeError('case question is required');const exactAggregates=value.exactAggregates==null?{}:obj(value.exactAggregates,'exactAggregates');return {id:value.id,question,requiredFacts:arr(value.requiredFacts).map(text),forbiddenClaims:arr(value.forbiddenClaims).map(text),exactAggregates:{...exactAggregates},requireDeterministic:Boolean(value.requireDeterministic),requireCompleteEvidence:Boolean(value.requireCompleteEvidence),tags:arr(value.tags).map(text)}}

export function evaluateFactRegression(inputCase,result={}){const testCase=normalizeFactRegressionCase(inputCase);obj(result,'fact regression result');const answer=text(result.answer);const requiredHits=testCase.requiredFacts.filter(fact=>includesFact(answer,fact));const forbiddenHits=testCase.forbiddenClaims.filter(claim=>includesFact(answer,claim));const aggregateSource=result.aggregates??result.metadata?.aggregates??{};const aggregateEntries=Object.entries(testCase.exactAggregates);const aggregateFailures=aggregateEntries.filter(([path,expected])=>readPath(aggregateSource,path)!==expected);const deterministicPass=!testCase.requireDeterministic||result.provider==='deterministic'||result.provenance==='deterministic';const evidence=result.evidence??result.metadata?.evidence??null;const completePass=!testCase.requireCompleteEvidence||evidence?.complete===true;const failures=[];for(const fact of testCase.requiredFacts.filter(fact=>!includesFact(answer,fact)))failures.push({type:'required-fact',value:fact});for(const claim of forbiddenHits)failures.push({type:'forbidden-claim',value:claim});for(const [path,expected] of aggregateFailures)failures.push({type:'exact-aggregate',path,expected,actual:readPath(aggregateSource,path)});if(!deterministicPass)failures.push({type:'non-deterministic-provenance'});if(!completePass)failures.push({type:'incomplete-evidence'});return {pass:failures.length===0,requiredFactCoverage:testCase.requiredFacts.length?requiredHits.length/testCase.requiredFacts.length:1,forbiddenClaimRate:testCase.forbiddenClaims.length?forbiddenHits.length/testCase.forbiddenClaims.length:0,exactAggregatePass:aggregateFailures.length===0,deterministicPass,completeEvidencePass:completePass,failures}}

export function buildCollectionRegressionCase(value){obj(value,'collection regression case');if(!Number.isFinite(value.expectedTotal))throw new TypeError('expectedTotal is required');const expected=String(value.expectedTotal);const requiredFacts=[...new Set([expected,...arr(value.requiredFacts).map(text)])];const forbiddenClaims=[...new Set([...arr(value.forbiddenTotals).map(text),...arr(value.forbiddenClaims).map(text)])];return normalizeFactRegressionCase({id:value.id,question:value.question??value.prompt,requiredFacts,forbiddenClaims,exactAggregates:{total:value.expectedTotal,...(value.exactAggregates??{})},requireDeterministic:value.requireDeterministic??false,requireCompleteEvidence:value.requireCompleteEvidence??false,tags:value.tags??[]})}
