const text=(v,l)=>{if(typeof v!=='string'||!v.trim())throw new TypeError(`${l} is required.`);return v.trim();};
const iso=(v,l)=>{const t=Date.parse(v);if(!Number.isFinite(t))throw new TypeError(`${l} must be a valid date.`);return new Date(t).toISOString();};
const SEVERITIES=new Set(['info','warning','critical']);
const PRIORITIES=new Set(['low','normal','high','urgent']);
export function createAlert({id,entityRef,title,dueAt,severity='info',metadata={}}={}){if(!entityRef?.kind||!entityRef?.id)throw new TypeError('Alert entityRef kind and id are required.');if(!SEVERITIES.has(severity))throw new TypeError('Alert severity must be info, warning or critical.');return Object.freeze({id:text(id,'Alert id'),entityRef:Object.freeze({kind:text(entityRef.kind,'Entity kind'),id:text(entityRef.id,'Entity id')}),title:text(title,'Alert title'),dueAt:iso(dueAt,'Alert dueAt'),severity,status:'active',snoozedUntil:null,acknowledgedAt:null,acknowledgedBy:null,dismissedAt:null,dismissedBy:null,dismissReason:null,metadata:Object.freeze({...metadata})});}
export function acknowledgeAlert(alert,{actorId,at=new Date().toISOString()}={}){if(alert.status==='dismissed')throw new Error('Dismissed alert cannot be acknowledged.');return Object.freeze({...alert,status:'acknowledged',acknowledgedAt:iso(at,'Acknowledged at'),acknowledgedBy:text(actorId,'Actor id')});}
export function snoozeAlert(alert,{until}={}){if(alert.status==='dismissed')throw new Error('Dismissed alert cannot be snoozed.');const value=iso(until,'Snooze until');if(Date.parse(value)<=Date.parse(alert.dueAt))throw new Error('Snooze must extend beyond dueAt.');return Object.freeze({...alert,status:'active',snoozedUntil:value});}
export function dismissAlert(alert,{actorId,reason,at=new Date().toISOString()}={}){return Object.freeze({...alert,status:'dismissed',dismissedAt:iso(at,'Dismissed at'),dismissedBy:text(actorId,'Actor id'),dismissReason:text(reason,'Dismiss reason')});}
export function listDueAlerts(alerts=[],{now=new Date().toISOString()}={}){const current=Date.parse(iso(now,'Current time'));return alerts.filter(alert=>alert?.status==='active'&&Date.parse(alert.snoozedUntil??alert.dueAt)<=current).sort((a,b)=>Date.parse(a.snoozedUntil??a.dueAt)-Date.parse(b.snoozedUntil??b.dueAt));}
export function createNotification({id,title,body='',priority='normal',entityRef=null,createdAt=new Date().toISOString(),metadata={}}={}){if(!PRIORITIES.has(priority))throw new TypeError('Notification priority must be low, normal, high or urgent.');if(entityRef&&(!entityRef.kind||!entityRef.id))throw new TypeError('Notification entityRef kind and id are required.');return Object.freeze({id:text(id,'Notification id'),title:text(title,'Notification title'),body:String(body),priority,entityRef:entityRef?Object.freeze({kind:text(entityRef.kind,'Entity kind'),id:text(entityRef.id,'Entity id')}):null,status:'unread',createdAt:iso(createdAt,'Notification createdAt'),readAt:null,readBy:null,metadata:Object.freeze({...metadata})});}
export function markNotificationRead(notification,{actorId=null,at=new Date().toISOString()}={}){if(notification.status==='read')return notification;return Object.freeze({...notification,status:'read',readAt:iso(at,'Notification readAt'),readBy:actorId==null?null:String(actorId)})}
export function listUnreadNotifications(notifications=[]){return notifications.filter(n=>n?.status==='unread').sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt))}
